name: New Huo Pool Client Due Diligence Form
description: New Huo Pool Client Due Diligence
title: "[New Huo Pool Client Due Diligence Form]:LDN Name /Issue # "
labels: ["DataCap", "Client"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: 
        Thanks for taking the time to fill out this form!
  - type: input
    id: name
    attributes: 
      label: Name
      description: What is your name?
      placeholder: e.g.Dwayne Johnson
    validations:
      required: true
  - type: input
    id: Affiliated-organization
    attributes:
      label: Affiliated organization
      description: What is your affiliated organization?
      placeholder: e.g. xxx Ltd. 
    validations:
      required: true
  - type: input
    id: 
    attributes:
      label: Proof of organizational affiliation
      description: Please email verification from your organization’s email to NewHuoPool@hotmail.com.
      placeholder: Sent/Unable to send(reason)
    validations:
      required: true
  - type: input
    id: 
    attributes:
      label: Dataset size
      description: What is the size of the original dataset?
      placeholder: 
    validations:
      required: true
  - type: input
    id: 
    attributes:
      label: The role related to the dataset
      description: Dataset Owner/Data Preparer/Other
      placeholder: 
    validations:
      required: true
  - type: input
    id: 
    attributes:
      label: Confidentiality
      description: Whether the data to be stored on Filecoin is subject to confidentiality, trade secret, national secrets or national security?
      placeholder: 
    validations:
      required: true
  - type: input
    id: 
    attributes:
      label: SPs info
      description: Please list all Storage Providers who you plan to use to store the datasetcopies(Miner ID/Entity Name/Email/Regions）
      placeholder: 
    validations:
      required: true
 
